### ISSUE TITLE
The icon.png file is installed in the wrong place

### ISSUE THREAD

**Issue by GvMariani** [pedrolcl/Linux-SonivoxEas#2]
Found while working on packaging Linux-SonivoxEas for ROSA Linux Fresh 2021.1.

At the install time, the icon file for guisynth.desktop get installed in /usr/icons/hicolor/128x128; see the guisynth/CMakeLists.txt snippet below:
`install( FILES ${CMAKE_CURRENT_SOURCE_DIR}/icon.png
         DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/128x128
         RENAME sonivoxeas.png `

However, this is the wrong place; AFAICT the right one for icons to be used in .desktop files should be /usr/icons/hicolor/128x128/apps...

**Comment by pedrolcl** [comment]
[v1.4.1 released](https://github.com/pedrolcl/Linux-SonivoxEas/releases/tag/v1.4.1)
