### ISSUE TITLE
Drumstick can now link to Qt5 or Qt6, in case it is linked with Qt6 SonivoxEas is not compatible ...

### ISSUE THREAD

**Issue by yurivict** [pedrolcl/Linux-SonivoxEas#3]
... because [here](https://github.com/pedrolcl/Linux-SonivoxEas/blob/master/libsvoxeas/CMakeLists.txt#L28) it uses Qt5.

**Comment by pedrolcl** [comment]
> because [here](https://github.com/pedrolcl/Linux-SonivoxEas/blob/master/libsvoxeas/CMakeLists.txt#L28) it uses Qt5.

Yes, there is a mistake there.  And another [here](https://github.com/pedrolcl/Linux-SonivoxEas/blob/master/guisynth/CMakeLists.txt#L23), and [another](https://github.com/pedrolcl/Linux-SonivoxEas/blob/master/cmdlnsynth/CMakeLists.txt#L8) one.

It will be fixed the next release, but: Linux-SonivoxEas is only for Linux, because it depends on the ALSA sequencer (indirectly, because it needs Drumstick::ALSA), which is not available outside Linux, AFAIK. There is another project: [multiplatform-sonivoxeas](https://github.com/pedrolcl/multiplatform-sonivoxeas) that is truly multiplatform, using Drumstick::RT instead (like VMPK).

**Comment by yurivict** [comment]
> ALSA sequencer (indirectly, because it needs Drumstick::ALSA), which is not available outside Linux, AFAIK

It is available on FreeBSD.

**Comment by pedrolcl** [comment]
I know [alsa-seq-server](https://www.gsp.com/cgi-bin/man.cgi?section=8&topic=ALSA-SEQ-SERVER) but it doesn't implement the sequencer feature yet (scheduling events), so the alsa-utils programs aplaymidi, arecordmidi and aseqdump can't work. drumstick-guiplayer, drumstick-drumgrid, and drumstick-playsmf don't work either.

It is promising, though,and it is a good idea to implement it as a daemon/service in user space, emulating (midi) character devices with cuse. I hope that some day it become complete.

**Comment by hselasky** [comment]
@pedrolcl : That's correct. If you want to add such support, feel free to submit patches!

**Comment by pedrolcl** [comment]
@hselasky :
> That's correct. If you want to add such support, feel free to submit patches!

One thing that @yurivict didn't told correctly is that this project (Linux-SonivoxEas) needs the sequencer feature. In fact, the sonivox library already implements sequencing by itself, and is capable of playing MIDI files without ALSA support.

On the other hand, I've named several programs belonging to the alsa-utils and the drumstick utilities that are depending on MIDI  scheduling, and would benefit from having this feature added. There are alternatives, of course: my dmidiplayer app is already ported to FreeBSD by Yuri, and it can play MIDI files with many extra features.

But believe it or not, my main interest is to implement the ALSA sequencer in user space ... FOR LINUX! and then port it to Android, which you probably know that doesn't include this subsystem. And why not: also to Windows!

Unfortunately, I'm currently starting a new (paid) project, and my free time will be scarce in the near future.

**Comment by pedrolcl** [comment]
[v1.4.1 released](https://github.com/pedrolcl/Linux-SonivoxEas/releases/tag/v1.4.1)

**Comment by hselasky** [comment]
Just added sequencer queue support to alsa-seq-server :-)

**Comment by hselasky** [comment]
FYI: https://cgit.freebsd.org/ports/commit/?id=3a57a5ea9a2d8a1397b6745ea55b14db7f21518b

(Fixes FreeBSD issues with ALSA sequencer queues)
