### ISSUE TITLE
SonivoxEas fails when PulseAudio was built without capabilities support

### ISSUE THREAD

**Issue by yurivict** [pedrolcl/Linux-SonivoxEas#4]
```
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Failed to create PulseAudio connection
Assertion 'p' failed at pulse/simple.c:273, function int pa_simple_write(pa_simple *, const void *, size_t, int *)(). Aborting.
Abort trap
```

Virtually all other applications using PulseAudio are able to work without capabilities support in PulseAudio, and SonivoxEas should work as well.

**Comment by yurivict** [comment]
```Failed to create PulseAudio connection``` should be a fatal error. ```qCritical()``` isn't sufficient.

**Comment by yurivict** [comment]
Please print the detailed reason why PulseAudio fails to connect.

The online example has this line:
> fprintf(stderr, "pa_simple_new() failed: %s\n", pa_strerror(error));

**Comment by yurivict** [comment]
The error code "Connection refused", but PulseAudio is running.

**Comment by yurivict** [comment]
Perhaps there is some problem with PulseAudio, but the above coding issues need to be fixed.

**Comment by pedrolcl** [comment]
[v1.4.1 released](https://github.com/pedrolcl/Linux-SonivoxEas/releases/tag/v1.4.1)
